DROP TABLE IF EXISTS memory_items;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS conversations;
DROP TABLE IF EXISTS chatbot_configs;
DROP TABLE IF EXISTS context_policies;
DROP TABLE IF EXISTS model_configs;
DROP TABLE IF EXISTS provider_configs;

CREATE TABLE provider_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    type VARCHAR(64) NOT NULL,
    base_url VARCHAR(1024),
    api_key_secret_ref VARCHAR(512),
    encrypted_api_key CLOB,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE model_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    model_name VARCHAR(200) NOT NULL,
    model_type VARCHAR(64) NOT NULL,
    max_context_tokens INTEGER,
    default_temperature DOUBLE PRECISION,
    default_top_p DOUBLE PRECISION,
    supports_streaming BOOLEAN NOT NULL,
    enabled BOOLEAN NOT NULL,
    metadata JSON NOT NULL,
    CONSTRAINT fk_model_provider FOREIGN KEY (provider_id) REFERENCES provider_configs(id)
);

CREATE TABLE context_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL UNIQUE,
    description CLOB,
    dsl_content CLOB NOT NULL,
    version INTEGER NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE chatbot_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL UNIQUE,
    description CLOB,
    default_model_id BIGINT,
    context_policy_id BIGINT,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_chatbot_model FOREIGN KEY (default_model_id) REFERENCES model_configs(id),
    CONSTRAINT fk_chatbot_policy FOREIGN KEY (context_policy_id) REFERENCES context_policies(id)
);

CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chatbot_id BIGINT NOT NULL,
    user_id VARCHAR(128),
    anonymous_session_id VARCHAR(128),
    title VARCHAR(240),
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_conversation_chatbot FOREIGN KEY (chatbot_id) REFERENCES chatbot_configs(id)
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    content CLOB NOT NULL,
    token_count INTEGER,
    metadata JSON NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id)
);

CREATE TABLE memory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chatbot_id BIGINT NOT NULL,
    user_id VARCHAR(128),
    scope VARCHAR(32) NOT NULL,
    content CLOB NOT NULL,
    embedding VARBINARY,
    metadata JSON NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_memory_chatbot FOREIGN KEY (chatbot_id) REFERENCES chatbot_configs(id)
);